[build]
builder = "NIXPACKS"
watchPatterns = ["api-gateway/**"]

[build.nixpacksConfig]
nodeVersion = "18"

[deploy]
startCommand = "npm run build && npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[experimental]
incremental = true
