version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chatbot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SUSER
      POSTGRES_DB: DBChatBot
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot_network

volumes:
  postgres_data:

networks:
  chatbot_network:
    driver: bridge
