[phases.setup]
nixpkgs = ["nodejs_18"]

[phases.install]
cmd = "npm install --legacy-peer-deps"

[phases.build]
cmd = "npx prisma generate && npm run build"

[start]
cmd = "npm run start:railway:safe"
