[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nodeVersion = "18"

[deploy]
startCommand = "npm run build && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[experimental]
incremental = true
